### ISSUE TITLE
Shiray: The CPU resources is near 100% all time and MEM consumption is high

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#151]
Shiray: It's a memory usage in 5 minutes after starting.
The configuration is set to monitor 3 directories with a total of 36555 files only.

The CPU resources is near 100% all time.
100% is a full usage of the single CPU's core.

**Comment by yarondbb** [comment]
Few cancidates for this ebehavior:
1. Monitoring and Indexing are working non-stop
2. For each monitoring event the entire content data structure is cloned twice (when writing to index output queue and when updating the dynamic content data) - concider updaintg only when there is a change. And clone it once - or think of incremental changes.. since this is all done locally)
3. Networking is exausting the system when xxxK files protocol is done.
   Concider requesting only xxx number of files copy at any compare event?
   more candidates ?

**Comment by bbfsdev** [comment]
Note that Shiray tested this on backup server with the following configuration:
Note the 5 minute scan period. We have to recreate the problem first.

```
# Paths to monitor/backup files from. 
# All path files and recursive sub paths are used.
monitoring_paths:
  - path: /mnt/storage/media/files
    scan_period: 300
    stable_state: 2
  - path: /mnt/storage/media/audio
    scan_period: 300
    stable_state: 2
  - path: /mnt/storage/media/video
    scan_period: 300
    stable_state: 2

# Backup folder
backup_destination_folder: '/mnt/storage/bbfs/backup'

# Default is nil
content_server_hostname: 'localhost'

# TCP/IP port to start server to send files to backup
content_server_files_port: 4444

# TCP/IP port to start server to send content data upon request from client
content_server_data_port: 3333

# Delay before trying to reconnect
client_retry_delay: 300

# backup data file, i.e. state(index) of backup server destination folder
local_content_data_path: '~/.bbfs/var/backup.data'

# Write all log messages to file
log_write_to_file: true
log_file_name: '~/.bbfs/log/backup_server.log4r'

# Write all log messages to standard output (default: false)
log_write_to_console: false

# Send errors to mail on system crush only (default: false)
log_write_to_email: false

# Verbosity of logging
# 0 will log INFO messages. 3 will print ALL debug messages as well.
log_debug_level: 0

# user should change to real value
from_email: 'jhon.doe@gmail.com'

# user should change to real value
from_email_password: 'hihahu'

# user should change to real value
to_email: 'jhon.doe@gmail.com'

# Log of file changes
default_monitoring_log_path: '~/.bbfs/log/backup_file_monitoring.log'

# Cycles of fetch period used by backup server to ping content server for its content
remote_content_save_timeout: 900

# Cycles where backup is checking if sync is required between remote and backup contents
backup_check_delay: 300

# Write all parameters to console on start
print_params_to_stdout: false
```
