### ISSUE TITLE
Update "backup_destination_folder" flag.

### ISSUE THREAD

**Issue by bbfsdev** [bbfsdev/bbfs#162]
Please don't use any more "backup_destination_folder".

```
On backup server, this path is taken from the list of monitoring_paths (the first one!!!).
monitoring_paths:
  - path: /mnt/storage/media/files
    scan_period: 300
    stable_state: 2
  - path: /mnt/storage/media/audio
    scan_period: 300
    stable_state: 2
  - path: /mnt/storage/media/video
    scan_period: 300
    stable_state: 2
```
